#!/usr/bin/env node

main();

async function main() {
  const { readFileSync, writeFileSync } = await import("fs");
  const { parseSfz } = await import("./lib/parse-sfz.mjs");

  const args = process.argv.slice(2);
  if (args.length < 1) {
    console.log("Usage: ./scripts/sfz2json <input.sfz> <output.json>");
    return;
  }

  const [inputPath, outputPath] = args;

  const sfzPath = inputPath.slice(0, inputPath.lastIndexOf("/") + 1);
  console.log(inputPath, sfzPath);
  const sfz = readFileSync(inputPath).toString();
  const json = parseSfz(sfz, (fileName) =>
    readFileSync(sfzPath + fileName).toString()
  );
  if (outputPath) {
    writeFileSync(outputPath, JSON.stringify(json, null, 2));
  } else {
    console.log(JSON.stringify(json));
  }
}
