#!/usr/bin/env node

main();

async function main() {
  const { readFileSync, writeFileSync } = await import("fs");
  const { parseSfz } = await import("./lib/parse-sfz.mjs");

  const args = process.argv.slice(2);
  if (args.length < 2) {
    console.log("Usage: ./scripts/sfz2json <input.sfz> <output.json>");
    return;
  }

  const [inputPath, outputPath] = args;

  const sfz = readFileSync(inputPath).toString();
  const json = parseSfz(sfz);
  writeFileSync(outputPath, JSON.stringify(json));
}
